In [3]:
print("Hello")

Hello


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


# **Introduction to Tensors**

## **Creating tensors**

In [5]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
# TENSOR
TENSOR = torch.tensor([[1,2,3],
                       [3,6,9],
                       [2,4,5]])

TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
TENSOR.ndim

2

In [16]:
TENSOR.shape

torch.Size([3, 3])

### Random tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numabers and then adjust those random numbers to better represent the data.

start with random -> look at data -> update random numbers -> look at data -> update random numbers

In [17]:
# Create a random tesnor of size(3,4)

random_tensor = torch.rand(3,4)

random_tensor

tensor([[0.1923, 0.4939, 0.4377, 0.0780],
        [0.5109, 0.6119, 0.6356, 0.3589],
        [0.1019, 0.3556, 0.5087, 0.4806]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size = (224,224,3)) # height, width, colour channel

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeors and Ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor od all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensor-like

In [24]:
# use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

**Note: ** Tensor data types is one of the 3 big errors you'll run into with PyTorch & Deep Learning :

1. Tensors not right datatype
2. Tenosors not right shape
3. Tensors not on the right device

In [27]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)

float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what data type is the tensor(e.g. float32 or float16)
                               device=None, # What device is your tensor on
                              requires_grad=False ) # whether or not to track gradients with this tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
 # int
 int_32_tensor = torch.tensor([3,6,9],
                              dtype = torch.int32)
 int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors(tensor attributes)

1. Tensors not right datatype -> to do get datatype from a tensor, can use `tensor.dtype`
2. Tenosors not right shape -> to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device -> to get device from a tensor, can use `tenor.device`

In [33]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2055, 0.0797, 0.9808, 0.1115],
        [0.6501, 0.2608, 0.4354, 0.0157],
        [0.3337, 0.4809, 0.1350, 0.8660]])

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tenosr is on : {some_tensor.device}")

tensor([[0.2055, 0.0797, 0.9808, 0.1115],
        [0.6501, 0.2608, 0.4354, 0.0157],
        [0.3337, 0.4809, 0.1350, 0.8660]])
Datatype of tensor : torch.float32
Shape of tensor: torch.Size([3, 4])
Device tenosr is on : cpu


### Manipulating Tensor (tensor operations)

Tensor operations include :
* Addition
* Subtraction
* Multiplication (element-wise)
* Devision
* Matrix multiplication

In [35]:
# Create a tensor and adding 10 to it
tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
# Subtracting 10
tensor-10

tensor([-9, -8, -7])

In [38]:
# Try out PyTorch in-built functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
torch.add(tensor,10)

tensor([11, 12, 13])

# Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning :

1. Element-wise Multiplication
2. Matrix multiplication (dot product `(.)`)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimension** must match :
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimension**:
* `(2,3) @ (2,2) -> (2,2)`
* `(3,2) @ (2,3) -> (3,3)`
  





In [40]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.03 ms, sys: 1.03 ms, total: 2.06 ms
Wall time: 2.2 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 95 µs, sys: 13 µs, total: 108 µs
Wall time: 112 µs


tensor(14)

## One of the most common errors in deep learning : shape error

In [48]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's a alias for writing less code  )
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate the shape of one of our tensor using a **transpose**

A **transpose** switches the axes or dimension of a given tensor

In [53]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [54]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [56]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [57]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [58]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimension must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimension must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc(tensor aggregation)

In [59]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [61]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [62]:
# Fibd the mean
torch.mean(x) # Because of int64

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [66]:
# Note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [67]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [68]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [70]:
x.argmin() # Find the position in tensor that has the minimum value with argmin() returns index position of target tensor where the minimum value occurs

tensor(0)

In [71]:
x[0]

tensor(0)

In [72]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [73]:
x[9]

tensor(90)

In [ ]:
 ## Reshaping, stacking, squuzing and unsqueezing tensors

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping -> reshapes an input tensor to a defined shape
* View -> Return a view of an input tensor of certain shape but keep the same memory as the orginal tenosr
* Stacking -> combine multiple tensor on top of each other (Vstack) or side by side (hstack)
* Squeeze - > remove all `1` dimensions from a tensor
* Unsqueeze -> add a `1` dimensions to a target tensor
Permute -> Return a view of the input with dimensions permuted (swapped) in a certain way

In [74]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [76]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [79]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [85]:
# torch.sqeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [81]:
x_reshaped.shape

torch.Size([1, 9])

In [82]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [83]:
x_reshaped.squeeze().shape

torch.Size([9])

In [86]:
#torch.unsqueeze() -> adds a single dimension to a target tensor at a specific dim (dimension)

print(f"Previous target : {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsq = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor : {x_unsq}")
print(f"New shape: {x_unsq.shape}")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [88]:
# torch.permute -> rearranges the dimension of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]


# Permute the orginal tensor to rearrange the axis (or dim) order
x_per = x_original.permute(2,0,1) # shifts axis 0->2, 1->0, 2-1

print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_per.shape}") # [colour_channels, height, width ]

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


# Indexing (selecting data from tensors)
indexing with PyTorch is similar to indexing with Numpy

In [89]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [90]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [91]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [92]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [93]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [94]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [96]:
# Get all values of the 0 dimension but only the 1 index value of 1srt and 2nd dimension
x[:,1,1]

tensor([5])

In [97]:
# Get index of 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [99]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


# PyTorch tensor & Numpy

Numpy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [100]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [101]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))