# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.9470, 0.0486, 0.9043, 0.5502, 0.9590, 0.2231, 0.7576],
        [0.1184, 0.3324, 0.0457, 0.5553, 0.9460, 0.3546, 0.3058],
        [0.5458, 0.2033, 0.6699, 0.5497, 0.9371, 0.7451, 0.2489],
        [0.2669, 0.0627, 0.4685, 0.3517, 0.5500, 0.9822, 0.6870],
        [0.7328, 0.1395, 0.1761, 0.6747, 0.9774, 0.3942, 0.1728],
        [0.0691, 0.5267, 0.6739, 0.2330, 0.1483, 0.3144, 0.1960],
        [0.8708, 0.6151, 0.7426, 0.7269, 0.1283, 0.1019, 0.2640]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [8]:
# Create another random tensor
another_tensor = torch.rand(1,7)

# Perform matrix multiplication 
another_tenosr = another_tensor.T
matrix = torch.matmul(random_tensor, another_tenosr)
matrix

tensor([[2.4846],
        [1.4663],
        [2.2793],
        [1.9884],
        [1.6860],
        [1.1715],
        [1.3871]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random = torch.rand(size=(7,7))
random_1 = torch.rand(size=(1,7))
# Matrix multiply tensors
# torch.matmul(maxtrix_tensor)
print(torch.matmul(input = random,other=random_1.T),torch.matmul(input = random,other=random_1.T).size())

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
torch.cuda.manual_seed(5224)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    print("cuda is  available")
else:
    print(" using CPU ")
# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3),device=None)
tensor_B  = torch.rand(size=(2,3),device=None)
print(tensor_A)
print( tensor_B)

 using CPU 
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [17]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A,tensor_B.T)
tensor_C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [18]:
# Find max
print(tensor_C.max())
# Find min
print(tensor_C.min())

tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [19]:
# Find arg max
print(tensor_C.argmax())

# Find arg min
print(tensor_C.argmin())

tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
